//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetProgrami.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiDetay
    {
        public int KisiDetayID { get; set; }
        public int KisiID { get; set; }
        public double Boy { get; set; }
        public double Kilo { get; set; }
        public double CalismaBicimi { get; set; }
        public Nullable<double> KaloriIhtiyaci { get; set; }
        public Nullable<double> VucutYuzeyAlani { get; set; }
        public Nullable<double> YagsizVucutAgirligi { get; set; }
        public Nullable<double> IdealKilo { get; set; }
        public Nullable<double> VucutKitleIndeksi { get; set; }
        public System.DateTime bilgiGuncellemeTarihi { get; set; }
    
        public virtual KisiTbl KisiTbl { get; set; }
    }
}
