//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiyetProgrami.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KisiTbl()
        {
            this.KisiDetay = new HashSet<KisiDetay>();
            this.OgunTbl = new HashSet<OgunTbl>();
        }
    
        public int KisiID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public bool Cinsiyet { get; set; }
        public System.DateTime DTarihi { get; set; }
        public System.DateTime kayitTarihi { get; set; }
        public int diyetisyenID { get; set; }
        public bool kisiAktif { get; set; }
        public string telefonNo { get; set; }
    
        public virtual DiyetisyenTbl DiyetisyenTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KisiDetay> KisiDetay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgunTbl> OgunTbl { get; set; }
    }
}
